"""Tests for exporters — tech debt exporter and status tracker exporter coverage."""

import tempfile
from datetime import datetime, date, timezone
from pathlib import Path

from models import WorkItem, Feature, ExportLog


# ── Tech Debt Exporter Tests ─────────────────────────────────


class TestTechDebtExporterRender:
    """Tests for TechDebtExporter.render() — markdown output correctness."""

    def test_render_with_active_items(self, app, db):
        """Render produces markdown with active item headers."""
        from exporters.tech_debt_exporter import TechDebtExporter

        db.session.add(
            WorkItem(
                project="test",
                source_id="TD-001",
                title="Fix auth bug",
                category="tech_debt",
                priority="high",
                status="backlog",
                notes="Auth is broken in production.",
            )
        )
        db.session.commit()

        exporter = TechDebtExporter()
        output = exporter.render("test")

        assert "AUTO-GENERATED by Polaris DevTools" in output
        assert "# Tech Debt Tracker" in output
        assert "## TD-001: Fix auth bug" in output
        assert "Auth is broken in production." in output
        assert "**Priority:** High" in output

    def test_render_with_deferred_item(self, app, db):
        """Deferred items get the *(Deferred)* suffix."""
        from exporters.tech_debt_exporter import TechDebtExporter

        db.session.add(
            WorkItem(
                project="test",
                source_id="TD-002",
                title="Legacy cleanup",
                category="tech_debt",
                status="deferred",
            )
        )
        db.session.commit()

        exporter = TechDebtExporter()
        output = exporter.render("test")

        assert "*(Deferred)*" in output

    def test_render_with_done_items_in_priority_table(self, app, db):
        """Done items get strikethrough in priority table."""
        from exporters.tech_debt_exporter import TechDebtExporter

        db.session.add(
            WorkItem(
                project="test",
                source_id="TD-003",
                title="Completed task",
                category="tech_debt",
                status="done",
                effort="S",
            )
        )
        db.session.commit()

        exporter = TechDebtExporter()
        output = exporter.render("test")

        assert "~~" in output  # Strikethrough for done items
        assert "✅" in output  # Done marker

    def test_render_with_resolved_archive(self, app, db):
        """Resolved (archived) items appear in the archive table."""
        from exporters.tech_debt_exporter import TechDebtExporter

        item = WorkItem(
            project="test",
            source_id="TD-010",
            title="Old resolved item",
            category="tech_debt",
            status="done",
            is_archived=True,
            resolution_summary="Fixed in v2.0",
        )
        item.completed_at = datetime(2026, 1, 15)
        db.session.add(item)
        db.session.commit()

        exporter = TechDebtExporter()
        output = exporter.render("test")

        assert "## Resolved Archive" in output
        assert "TD-010" in output
        assert "Old resolved item" in output
        assert "Fixed in v2.0" in output
        assert "2026-01-15" in output

    def test_render_with_identified_date(self, app, db):
        """Items with identified_date show the Created metadata."""
        from exporters.tech_debt_exporter import TechDebtExporter

        db.session.add(
            WorkItem(
                project="test",
                source_id="TD-004",
                title="Dated item",
                category="tech_debt",
                identified_date=date(2026, 2, 10),
            )
        )
        db.session.commit()

        exporter = TechDebtExporter()
        output = exporter.render("test")

        assert "**Created:** 2026-02-10" in output

    def test_render_empty_project(self, app, db):
        """Render with no items still produces valid markdown."""
        from exporters.tech_debt_exporter import TechDebtExporter

        exporter = TechDebtExporter()
        output = exporter.render("test")

        assert "# Tech Debt Tracker" in output
        # No Priority Order or Resolved Archive sections
        assert "## Priority Order" not in output
        assert "## Resolved Archive" not in output

    def test_render_medium_priority_omits_badge(self, app, db):
        """Medium priority items don't show the Priority badge (it's the default)."""
        from exporters.tech_debt_exporter import TechDebtExporter

        db.session.add(
            WorkItem(
                project="test",
                source_id="TD-005",
                title="Medium item",
                category="tech_debt",
                priority="medium",
            )
        )
        db.session.commit()

        exporter = TechDebtExporter()
        output = exporter.render("test")

        assert "**Priority:**" not in output


class TestTechDebtExporterExport:
    """Tests for TechDebtExporter.export() — file writing and stats."""

    def test_export_writes_file_and_records(self, app, db):
        """Export writes markdown file and creates ExportLog."""
        from exporters.tech_debt_exporter import TechDebtExporter

        db.session.add(
            WorkItem(
                project="test",
                source_id="TD-001",
                title="Test item",
                category="tech_debt",
            )
        )
        db.session.commit()

        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "tech_debt.md"
            exporter = TechDebtExporter()
            stats = exporter.export("test", output_path)

            assert stats["active"] == 1
            assert stats["resolved"] == 0
            assert stats["total"] == 1
            assert output_path.exists()

            content = output_path.read_text(encoding="utf-8")
            assert "TD-001" in content

            # ExportLog should be created
            log = ExportLog.query.filter_by(project="test", target="tech_debt").first()
            assert log is not None
            assert log.record_count == 1


# ── Status Tracker Exporter Tests ─────────────────────────────────


class TestStatusTrackerExporterRender:
    """Tests for StatusTrackerExporter.render() — markdown output correctness."""

    def test_render_with_features(self, app, db):
        """Render produces markdown with domain sections and status symbols."""
        from exporters.status_tracker_exporter import StatusTrackerExporter

        db.session.add_all(
            [
                Feature(
                    project="test",
                    name="Login feature",
                    requirement_id="FR-001",
                    domain="Authentication",
                    implementation_status="implemented",
                ),
                Feature(
                    project="test",
                    name="Signup feature",
                    requirement_id="FR-002",
                    domain="Authentication",
                    implementation_status="pending",
                ),
                Feature(
                    project="test",
                    name="Dashboard",
                    requirement_id="FR-003",
                    domain="UI",
                    implementation_status="partial",
                ),
            ]
        )
        db.session.commit()

        exporter = StatusTrackerExporter()
        output = exporter.render("test")

        assert "# VMS Development Status Tracker" in output
        assert "## Status Legend" in output
        assert "## Quick Summary" in output
        assert "## Authentication" in output
        assert "## UI" in output
        assert "FR-001" in output
        assert "✅" in output  # implemented
        assert "📋" in output  # pending
        assert "🔧" in output  # partial
        assert "~3" in output  # Total count

    def test_render_summary_table_counts(self, app, db):
        """Summary table shows correct counts per domain."""
        from exporters.status_tracker_exporter import StatusTrackerExporter

        db.session.add_all(
            [
                Feature(
                    project="test",
                    name="F1",
                    requirement_id="FR-001",
                    domain="Core",
                    implementation_status="implemented",
                ),
                Feature(
                    project="test",
                    name="F2",
                    requirement_id="FR-002",
                    domain="Core",
                    implementation_status="implemented",
                ),
                Feature(
                    project="test",
                    name="F3",
                    requirement_id="FR-003",
                    domain="Core",
                    implementation_status="pending",
                ),
            ]
        )
        db.session.commit()

        exporter = StatusTrackerExporter()
        output = exporter.render("test")

        # The summary table should contain the Core domain
        assert "Core" in output
        # Should show 3 total features somewhere
        assert "| 3 " in output

    def test_render_feature_with_test_cases(self, app, db):
        """Features with test cases show them in the notes column."""
        from exporters.status_tracker_exporter import StatusTrackerExporter

        f = Feature(
            project="test",
            name="Feature with tests",
            requirement_id="FR-010",
            domain="Testing",
            implementation_status="implemented",
            notes="TC-100, TC-101",
        )
        db.session.add(f)
        db.session.commit()

        exporter = StatusTrackerExporter()
        output = exporter.render("test")

        assert "TC-100" in output
        assert "TC-101" in output

    def test_render_empty_project(self, app, db):
        """Render with no features produces valid markdown."""
        from exporters.status_tracker_exporter import StatusTrackerExporter

        exporter = StatusTrackerExporter()
        output = exporter.render("test")

        assert "# VMS Development Status Tracker" in output
        assert "~0" in output


class TestStatusTrackerExporterExport:
    """Tests for StatusTrackerExporter.export() — file writing and stats."""

    def test_export_writes_file_and_records(self, app, db):
        """Export writes markdown and creates ExportLog with status counts."""
        from exporters.status_tracker_exporter import StatusTrackerExporter

        db.session.add_all(
            [
                Feature(
                    project="test",
                    name="F1",
                    requirement_id="FR-001",
                    domain="Core",
                    implementation_status="implemented",
                ),
                Feature(
                    project="test",
                    name="F2",
                    requirement_id="FR-002",
                    domain="Core",
                    implementation_status="partial",
                ),
                Feature(
                    project="test",
                    name="F3",
                    requirement_id="FR-003",
                    domain="Core",
                    implementation_status="pending",
                ),
            ]
        )
        db.session.commit()

        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "status_tracker.md"
            exporter = StatusTrackerExporter()
            stats = exporter.export("test", output_path)

            assert stats["total"] == 3
            assert stats["implemented"] == 1
            assert stats["partial"] == 1
            assert stats["pending"] == 1
            assert output_path.exists()

            # ExportLog created
            log = ExportLog.query.filter_by(
                project="test", target="status_tracker"
            ).first()
            assert log is not None
            assert log.record_count == 3


# ── BaseExporter Tests ─────────────────────────────────


class TestBaseExporter:
    """Tests for BaseExporter utilities."""

    def test_is_dirty_when_never_exported(self, app, db):
        """is_dirty returns True when no prior export exists."""
        from exporters.base import BaseExporter

        exporter = BaseExporter()
        assert (
            exporter.is_dirty("test", "tech_debt", datetime.now(timezone.utc)) is True
        )

    def test_is_dirty_when_records_updated(self, app, db):
        """is_dirty returns True when records updated after last export."""
        from exporters.base import BaseExporter

        exporter = BaseExporter()
        exporter.record_export("test", "tech_debt", "/tmp/test.md", 1)

        from datetime import timedelta

        future = datetime.now(timezone.utc) + timedelta(hours=1)
        assert exporter.is_dirty("test", "tech_debt", future) is True

    def test_is_not_dirty_when_no_changes(self, app, db):
        """is_dirty returns False when no records changed since export."""
        from exporters.base import BaseExporter

        exporter = BaseExporter()
        exporter.record_export("test", "tech_debt", "/tmp/test.md", 1)

        from datetime import timedelta

        past = datetime.now(timezone.utc) - timedelta(hours=1)
        assert exporter.is_dirty("test", "tech_debt", past) is False

    def test_table_helper(self):
        """Table helper renders a valid markdown table."""
        from exporters.base import BaseExporter

        result = BaseExporter.table(["A", "B"], [["1", "2"], ["3", "4"]])
        assert "| A | B |" in result
        assert "| 1 | 2 |" in result
        assert "| --- | --- |" in result

    def test_status_badge(self):
        """Status badge maps statuses to emoji."""
        from exporters.base import BaseExporter

        assert BaseExporter.status_badge("implemented") == "✅"
        assert BaseExporter.status_badge("unknown_status") == "❓"
