"""Base export engine with markdown helpers and dirty-flag tracking."""

from datetime import datetime, timezone
from pathlib import Path

from models import db, ExportLog


class BaseExporter:
    """Base class for DB → markdown exporters.

    Subclasses implement `render()` to produce markdown from DB records.
    The base handles dirty detection, file writing, and git staging.
    """

    format_key = ""  # Override in subclass

    # --- Dirty Detection ---

    def last_export_time(self, project: str, target: str) -> datetime | None:
        """Get the timestamp of the last export for this target."""
        log = (
            ExportLog.query.filter_by(project=project, target=target)
            .order_by(ExportLog.exported_at.desc())
            .first()
        )
        return log.exported_at if log else None

    def is_dirty(self, project: str, target: str, latest_update: datetime) -> bool:
        """Check if records have changed since last export."""
        last = self.last_export_time(project, target)
        if last is None:
            return True  # Never exported
        # Normalize to naive UTC for comparison (SQLite strips timezone info)
        last_naive = last.replace(tzinfo=None) if last.tzinfo else last
        update_naive = (
            latest_update.replace(tzinfo=None)
            if latest_update.tzinfo
            else latest_update
        )
        return update_naive > last_naive

    # --- File Writing ---

    def write_file(self, content: str, output_path: Path) -> None:
        """Write rendered markdown to the output file."""
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

    def record_export(
        self, project: str, target: str, file_path: str, record_count: int
    ) -> ExportLog:
        """Record an export in the log (for dirty-flag tracking)."""
        log = ExportLog(
            project=project,
            target=target,
            file_path=file_path,
            record_count=record_count,
            exported_at=datetime.now(timezone.utc),
        )
        db.session.add(log)
        db.session.commit()
        return log

    # --- Git Staging ---

    def git_stage(self, file_path: Path, project_root: Path) -> bool:
        """Stage the exported file in git.

        Returns True if staging succeeded, False otherwise.
        """
        try:
            import git

            repo = git.Repo(str(project_root))
            # Get path relative to repo root
            rel_path = file_path.relative_to(project_root)
            repo.index.add([str(rel_path)])
            return True
        except Exception:
            return False

    # --- Markdown Helpers ---

    @staticmethod
    def header(text: str, level: int = 1) -> str:
        """Render a markdown header."""
        return f"{'#' * level} {text}"

    @staticmethod
    def auto_generated_notice(export_time: datetime | None = None) -> str:
        """Render the auto-generated file header."""
        timestamp = (export_time or datetime.now(timezone.utc)).strftime(
            "%Y-%m-%d %H:%M:%S"
        )
        return (
            "<!-- ┌─────────────────────────────────────────────────────────────┐ -->\n"
            "<!-- │ AUTO-GENERATED by Polaris DevTools                         │ -->\n"
            f"<!-- │ Last exported: {timestamp:<44s}│ -->\n"
            "<!-- │ Edit via DevTools UI or CLI, not directly in this file.    │ -->\n"
            "<!-- └─────────────────────────────────────────────────────────────┘ -->\n"
        )

    @staticmethod
    def table(headers: list[str], rows: list[list[str]]) -> str:
        """Render a markdown table."""
        lines = []
        lines.append("| " + " | ".join(headers) + " |")
        lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
        for row in rows:
            lines.append("| " + " | ".join(str(c) for c in row) + " |")
        return "\n".join(lines)

    @staticmethod
    def status_badge(status: str) -> str:
        """Convert a status string to an emoji badge."""
        badges = {
            "implemented": "✅",
            "partial": "🔧",
            "pending": "📋",
            "future": "🔮",
            "na": "➖",
            "done": "✅",
            "in_progress": "🔧",
            "backlog": "📋",
            "deferred": "⏸️",
        }
        return badges.get(status, "❓")

    # --- Abstract (subclasses implement) ---

    def render(self, records, project_config) -> str:
        """Render DB records to a markdown string.

        Override in subclass.
        """
        raise NotImplementedError("Subclasses must implement render()")
