"""Changelog Exporter — render done WorkItems to a changelog markdown file.

Groups completed work items by month and category:
1. Features
2. Bug Fixes
3. Tech Debt
4. Cleanup / Other
"""

from collections import OrderedDict
from datetime import datetime, timezone
from pathlib import Path

from exporters.base import BaseExporter
from models import WorkItem


# Category display order and labels
CATEGORY_ORDER = OrderedDict(
    [
        ("feature", "Features"),
        ("bug", "Bug Fixes"),
        ("tech_debt", "Tech Debt"),
        ("cleanup", "Cleanup"),
        ("review", "Reviews"),
    ]
)


class ChangelogExporter(BaseExporter):
    """Export done WorkItems to a changelog.md file."""

    format_key = "changelog_v1"

    def render(self, project: str, project_config=None) -> str:
        """Render all done WorkItems to a changelog markdown string.

        Args:
            project: Project key to filter WorkItems.
            project_config: Optional project config (for path resolution).

        Returns:
            Full markdown string with items grouped by month and category.
        """
        export_time = datetime.now(timezone.utc)

        # Query all done items, newest first
        items = (
            WorkItem.query.filter_by(project=project, status="done")
            .order_by(WorkItem.updated_at.desc())
            .all()
        )

        parts = []

        # Auto-generated notice
        parts.append(self.auto_generated_notice(export_time))
        parts.append("")

        # Header
        parts.append(self.header("Changelog"))
        parts.append("")
        parts.append(
            "Work items completed in this project, grouped by month and category."
        )
        parts.append("")

        if not items:
            parts.append("*No completed items yet.*")
            parts.append("")
            return "\n".join(parts)

        # Group by month (YYYY-MM)
        months = OrderedDict()
        for item in items:
            ts = item.updated_at or item.created_at
            if ts is None:
                month_key = "Unknown"
                month_label = "Unknown Date"
            else:
                month_key = ts.strftime("%Y-%m")
                month_label = ts.strftime("%B %Y")
            if month_key not in months:
                months[month_key] = {"label": month_label, "items": []}
            months[month_key]["items"].append(item)

        # Render each month
        for month_key, month_data in months.items():
            parts.append(f"## {month_data['label']}")
            parts.append("")

            # Group by category within the month
            by_category = {}
            for item in month_data["items"]:
                cat = item.category or "feature"
                if cat not in by_category:
                    by_category[cat] = []
                by_category[cat].append(item)

            # Render categories in order
            for cat_key, cat_label in CATEGORY_ORDER.items():
                cat_items = by_category.pop(cat_key, [])
                if cat_items:
                    parts.append(f"### {cat_label}")
                    parts.append("")
                    for item in cat_items:
                        sid = f"**{item.source_id}** " if item.source_id else ""
                        parts.append(f"- {sid}{item.title}")
                    parts.append("")

            # Any remaining categories not in CATEGORY_ORDER
            for cat_key, cat_items in by_category.items():
                cat_label = cat_key.replace("_", " ").title()
                parts.append(f"### {cat_label}")
                parts.append("")
                for item in cat_items:
                    sid = f"**{item.source_id}** " if item.source_id else ""
                    parts.append(f"- {sid}{item.title}")
                parts.append("")

        # Footer
        parts.append("---")
        parts.append("")
        parts.append(
            f"*Generated by Polaris DevTools — {export_time.strftime('%Y-%m-%d')}*"
        )
        parts.append("")

        return "\n".join(parts)

    def export(self, project: str, output_path: Path, project_config=None) -> dict:
        """Render and write the changelog to a file.

        Args:
            project: Project key.
            output_path: Path to write the changelog.
            project_config: Optional project config.

        Returns:
            Dict with export stats.
        """
        content = self.render(project, project_config)
        self.write_file(content, output_path)

        # Count items for the log
        count = WorkItem.query.filter_by(project=project, status="done").count()

        self.record_export(project, "changelog", str(output_path), count)

        return {
            "file": str(output_path),
            "record_count": count,
        }
